spring:
  view:
    prefix: /WEB-INF/
    suffix: .jsp
    view-names: views/*
  thymeleaf:
    cache: false
    enabled: true
    view-names: thymeleaf/*
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
      use_sql_comments: false
      format_sql: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  batch:
    job:
      enabled: false
    initialize-schema: always

minut:
  project:
    start: 68
    end: 10528
  player:
    start: 1
    end: 36211
  team:
    start: 1
    end: 21967
